application: discussionpieces
version: 1
runtime: python
api_version: 1

skip_files: (^|/)(\.|RCS/|(app|index)\.ya?ml)|(\.py[co]|~)$

handlers:
    - url: /assets
      static_dir: assets
    
    - url: /.*
      script: main.py
