
from google.appengine.ext import db

class Piece(db.Model):
    creator = db.UserProperty()
    x       = db.IntegerProperty()
    y       = db.IntegerProperty()
    icon    = db.StringProperty()
    name    = db.StringProperty()
    desc    = db.TextProperty()

ICONS = (
{ "filename": "alertbot_32.png", "title": "Alertbot" },
{ "filename": "angry_32.png", "title": "Angry" },
{ "filename": "arctic-landscape_32.png", "title": "Arctic Landscape" },
{ "filename": "art_32.png", "title": "Art" },
{ "filename": "bag_blue_1_32.png", "title": "Bag Blue 1" },
{ "filename": "bag_blue_2_32.png", "title": "Bag Blue 2" },
{ "filename": "bag_green_32.png", "title": "Bag Green" },
{ "filename": "bag_magenta_32.png", "title": "Bag Magenta" },
{ "filename": "bag_orange_32.png", "title": "Bag Orange" },
{ "filename": "bag_yellow_32.png", "title": "Bag Yellow" },
{ "filename": "ball_blue_1_32.png", "title": "Ball Blue 1" },
{ "filename": "ball_blue_2_32.png", "title": "Ball Blue 2" },
{ "filename": "ball_green_32.png", "title": "Ball Green" },
{ "filename": "ball_magenta_32.png", "title": "Ball Magenta" },
{ "filename": "ball_orange_32.png", "title": "Ball Orange" },
{ "filename": "ball_yellow_32.png", "title": "Ball Yellow" },
{ "filename": "basset-hound_32.png", "title": "Basset Hound" },
{ "filename": "battery_32.png", "title": "Battery" },
{ "filename": "beagle_32.png", "title": "Beagle" },
{ "filename": "bones_32.png", "title": "Bones" },
{ "filename": "bread_32.png", "title": "Bread" },
{ "filename": "bubble_32.png", "title": "Bubble" },
{ "filename": "bug_32.png", "title": "Bug" },
{ "filename": "bulb_32.png", "title": "Bulb" },
{ "filename": "bulldog_32.png", "title": "Bulldog" },
{ "filename": "car_blue_32.png", "title": "Car Blue" },
{ "filename": "car_copper_32.png", "title": "Car Copper" },
{ "filename": "car_gold_32.png", "title": "Car Gold" },
{ "filename": "car_red_32.png", "title": "Car Red" },
{ "filename": "car_silver_32.png", "title": "Car Silver" },
{ "filename": "cassette_32.png", "title": "Cassette" },
{ "filename": "Cerveza_32.png", "title": "Cerveza" },
{ "filename": "cheese_32.png", "title": "Cheese" },
{ "filename": "chuckle_32.png", "title": "Chuckle" },
{ "filename": "clover_32.png", "title": "Clover" },
{ "filename": "club_32.png", "title": "Club" },
{ "filename": "command_32.png", "title": "Command" },
{ "filename": "computebot_32.png", "title": "Computebot" },
{ "filename": "cookie_32.png", "title": "Cookie" },
{ "filename": "critter_32.png", "title": "Critter" },
{ "filename": "crown_32.png", "title": "Crown" },
{ "filename": "cycle_blue_32.png", "title": "Cycle Blue" },
{ "filename": "cycle_copper_32.png", "title": "Cycle Copper" },
{ "filename": "cycle_gold_32.png", "title": "Cycle Gold" },
{ "filename": "cycle_red_32.png", "title": "Cycle Red" },
{ "filename": "cycle_silver_32.png", "title": "Cycle Silver" },
{ "filename": "daffodil_32.png", "title": "Daffodil" },
{ "filename": "daisy_32.png", "title": "Daisy" },
{ "filename": "dark_hero_32.png", "title": "Dark Hero" },
{ "filename": "deadly_32.png", "title": "Deadly" },
{ "filename": "devilish_32.png", "title": "Devilish" },
{ "filename": "diamond_32.png", "title": "Diamond" },
{ "filename": "digital_32.png", "title": "Digital" },
{ "filename": "dog_biscuit_32.png", "title": "Dog Biscuit" },
{ "filename": "drop_32.png", "title": "Drop" },
{ "filename": "electrical_32.png", "title": "Electrical" },
{ "filename": "embarrassed_32.png", "title": "Embarrassed" },
{ "filename": "eskimo-building_32.png", "title": "Eskimo Building" },
{ "filename": "eskimo-fishing_32.png", "title": "Eskimo Fishing" },
{ "filename": "executed_32.png", "title": "Executed" },
{ "filename": "explorer_32.png", "title": "Explorer" },
{ "filename": "Extraterrestrial_32.png", "title": "Extraterrestrial" },
{ "filename": "fallout_32.png", "title": "Fallout" },
{ "filename": "female_32.png", "title": "Female" },
{ "filename": "fezzed_32.png", "title": "Fezzed" },
{ "filename": "film_32.png", "title": "Film" },
{ "filename": "firewheel_32.png", "title": "Firewheel" },
{ "filename": "fortune_32.png", "title": "Fortune" },
{ "filename": "frownie_32.png", "title": "Frownie" },
{ "filename": "gear_32.png", "title": "Gear" },
{ "filename": "goldfish_32.png", "title": "Goldfish" },
{ "filename": "greedy_32.png", "title": "Greedy" },
{ "filename": "grin_32.png", "title": "Grin" },
{ "filename": "groucho_32.png", "title": "Groucho" },
{ "filename": "grumbling_32.png", "title": "Grumbling" },
{ "filename": "hand-saw_32.png", "title": "Hand Saw" },
{ "filename": "har_dee_har_32.png", "title": "Har Dee Har" },
{ "filename": "hazardbot_32.png", "title": "Hazardbot" },
{ "filename": "heart_32.png", "title": "Heart" },
{ "filename": "he_32.png", "title": "He" },
{ "filename": "icons.txt", "title": "Icons.txt" },
{ "filename": "igloo_32.png", "title": "Igloo" },
{ "filename": "infinity_32.png", "title": "Infinity" },
{ "filename": "inspectbot_32.png", "title": "Inspectbot" },
{ "filename": "King_of_Beasts_32.png", "title": "King Of Beasts" },
{ "filename": "kissy_32.png", "title": "Kissy" },
{ "filename": "labrador_32.png", "title": "Labrador" },
{ "filename": "Lipstick_32.png", "title": "Lipstick" },
{ "filename": "lizard_32.png", "title": "Lizard" },
{ "filename": "logo_32.png", "title": "Logo" },
{ "filename": "LP_32.png", "title": "LP" },
{ "filename": "male_32.png", "title": "Male" },
{ "filename": "meat_32.png", "title": "Meat" },
{ "filename": "militant_32.png", "title": "Militant" },
{ "filename": "muerte_32.png", "title": "Muerte" },
{ "filename": "ninja_32.png", "title": "Ninja" },
{ "filename": "orange_32.png", "title": "Orange" },
{ "filename": "otherworldly_32.png", "title": "Otherworldly" },
{ "filename": "PackRat_32.png", "title": "PackRat" },
{ "filename": "pancake_32.png", "title": "Pancake" },
{ "filename": "parakeet_32.png", "title": "Parakeet" },
{ "filename": "peace_32.png", "title": "Peace" },
{ "filename": "penguin_32.png", "title": "Penguin" },
{ "filename": "pest_32.png", "title": "Pest" },
{ "filename": "petunia_32.png", "title": "Petunia" },
{ "filename": "pickle_32.png", "title": "Pickle" },
{ "filename": "pickup_blue_32.png", "title": "Pickup Blue" },
{ "filename": "pickup_copper_32.png", "title": "Pickup Copper" },
{ "filename": "pickup_gold_32.png", "title": "Pickup Gold" },
{ "filename": "pickup_red_32.png", "title": "Pickup Red" },
{ "filename": "pickup_silver_32.png", "title": "Pickup Silver" },
{ "filename": "pineapple_32.png", "title": "Pineapple" },
{ "filename": "pins_32.png", "title": "Pins" },
{ "filename": "pizza_32.png", "title": "Pizza" },
{ "filename": "polar-bear-cub_32.png", "title": "Polar Bear Cub" },
{ "filename": "polar-bear_32.png", "title": "Polar Bear" },
{ "filename": "purple-marigold_32.png", "title": "Purple Marigold" },
{ "filename": "Raft_32.png", "title": "Raft" },
{ "filename": "red-marigold_32.png", "title": "Red Marigold" },
{ "filename": "scottish-terrier_32.png", "title": "Scottish Terrier" },
{ "filename": "scubabot_32.png", "title": "Scubabot" },
{ "filename": "scuba_32.png", "title": "Scuba" },
{ "filename": "seasick_32.png", "title": "Seasick" },
{ "filename": "securitybot_32.png", "title": "Securitybot" },
{ "filename": "sentinelbot_32.png", "title": "Sentinelbot" },
{ "filename": "servicebot_32.png", "title": "Servicebot" },
{ "filename": "shades_32.png", "title": "Shades" },
{ "filename": "sheesh_32.png", "title": "Sheesh" },
{ "filename": "she_32.png", "title": "She" },
{ "filename": "shirt_blue_1_32.png", "title": "Shirt Blue 1" },
{ "filename": "shirt_blue_2_32.png", "title": "Shirt Blue 2" },
{ "filename": "shirt_green_32.png", "title": "Shirt Green" },
{ "filename": "shirt_magenta_32.png", "title": "Shirt Magenta" },
{ "filename": "shirt_orange_32.png", "title": "Shirt Orange" },
{ "filename": "shirt_yellow_32.png", "title": "Shirt Yellow" },
{ "filename": "shock_32.png", "title": "Shock" },
{ "filename": "shoes_blue_1_32.png", "title": "Shoes Blue 1" },
{ "filename": "shoes_blue_2_32.png", "title": "Shoes Blue 2" },
{ "filename": "shoes_green_32.png", "title": "Shoes Green" },
{ "filename": "shoes_magenta_32.png", "title": "Shoes Magenta" },
{ "filename": "shoes_orange_32.png", "title": "Shoes Orange" },
{ "filename": "shoes_yellow_32.png", "title": "Shoes Yellow" },
{ "filename": "siamese_32.png", "title": "Siamese" },
{ "filename": "sign_1_32.png", "title": "Sign 1" },
{ "filename": "sign_2_32.png", "title": "Sign 2" },
{ "filename": "skateboard_32.png", "title": "Skateboard" },
{ "filename": "sliding-penguin_32.png", "title": "Sliding Penguin" },
{ "filename": "smilenstein_32.png", "title": "Smilenstein" },
{ "filename": "smiley_32.png", "title": "Smiley" },
{ "filename": "smylon_32.png", "title": "Smylon" },
{ "filename": "snowman-fishing_32.png", "title": "Snowman Fishing" },
{ "filename": "snowsmiley_32.png", "title": "Snowsmiley" },
{ "filename": "spade_32.png", "title": "Spade" },
{ "filename": "star_32.png", "title": "Star" },
{ "filename": "striped-french-marigold_32.png", "title": "Striped French Marigold" },
{ "filename": "surprised_32.png", "title": "Surprised" },
{ "filename": "tan-cat_32.png", "title": "Tan Cat" },
{ "filename": "tortie_32.png", "title": "Tortie" },
{ "filename": "wink_32.png", "title": "Wink" },
{ "filename": "yelling_32.png", "title": "Yelling" },
{ "filename": "yellow-daisy_32.png", "title": "Yellow Daisy" },
{ "filename": "yellow-marigold-2_32.png", "title": "Yellow Marigold 2" },
{ "filename": "yellow-marigold_32.png", "title": "Yellow Marigold" },
{ "filename": "yellow-submarine_32.png", "title": "Yellow Submarine" },
{ "filename": "yin_yang_32.png", "title": "Yin Yang" },
{ "filename": "yorick_32.png", "title": "Yorick" },
)
