#!/usr/bin/env python -i

import sys
sys.path += ('/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine',)
sys.path += ['/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/' + x for x in ('django', 'webob')]
sys.path += ('/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/yaml/lib',)


from google.appengine.api import apiproxy_stub_map, datastore_file_stub, mail_stub, urlfetch_stub, user_service_stub

apiproxy_stub_map.apiproxy = apiproxy_stub_map.APIProxyStubMap()

stubs = {
    'urlfetch': urlfetch_stub.URLFetchServiceStub,
    'mail':     mail_stub.MailServiceStub,
    'user':     user_service_stub.UserServiceStub,
}

for kind, stubclass in stubs.iteritems():
    apiproxy_stub_map.apiproxy.RegisterStub(kind, stubclass())

import os.path
here = os.path.dirname(__file__)

datastub = datastore_file_stub.DatastoreFileStub(
    'discussion-pieces',
    os.path.join(here, 'data', 'datastore'),
    os.path.join(here, 'data', 'history')
)
apiproxy_stub_map.apiproxy.RegisterStub('datastore_v3', datastub)


from main import *
